<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.ledsoft</groupId>
        <artifactId>jopa-utils</artifactId>
        <version>0.2.0</version>
    </parent>

    <artifactId>jopa-query-utils</artifactId>
    <name>JOPA Query Utilities</name>
    <description>
        Utilities for working with JOPA queries.
    </description>

    <dependencies>
        <dependency>
            <groupId>cz.cvut.kbss.jopa</groupId>
            <artifactId>jopa-api</artifactId>
            <version>${cz.cvut.kbss.jopa.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cz.cvut.kbss.jopa</groupId>
            <artifactId>jopa-impl</artifactId>
            <version>${cz.cvut.kbss.jopa.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cz.cvut.kbss.jopa</groupId>
            <artifactId>ontodriver-rdf4j</artifactId>
            <version>${cz.cvut.kbss.jopa.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>cz.cvut.kbss.jopa</groupId>
                <artifactId>jopa-maven-plugin</artifactId>
                <version>${cz.cvut.kbss.jopa.version}</version>
                <executions>
                    <execution>
                        <id>generate-static-metamodel</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>modelgen</goal>
                        </goals>
                        <configuration>
                            <source-package>com.github.ledsoft.jopa.util</source-package>
                            <additional-sources>${project.basedir}/src/test/java</additional-sources>
                            <output-directory>${project.build.directory}/generated-test-sources</output-directory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>add-generated-test-sources</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-test-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>